platform :ios, '12.0'
use_frameworks!

target 'demo' do
    pod 'CardIO'
    pod 'SDWebImage'

#    pod 'Cloudpayments', :git =>  "https://github.com/cloudpayments/CloudPayments-SDK-iOS", :branch => "master"
    pod 'Cloudpayments', :path => "../sdk"

end
